theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
rulers = [100]
auto-save = true

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1
