[language-server.typos]
command = "typos-lsp"

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]


[[language]]
name = "dockerfile"
language-servers = [ "docker-langserver", "typos" ]

[[language]]
name = "php"
language-servers = [ "intelephense", "typos" ]

[[language]]
name = "sql"
language-servers = [ "sql-language-server", "typos" ]

[[language]]
name = "bash"
language-servers = [ "bash-language-server", "typos" ]

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "typos" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "typos" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "git-commit"
language-servers = [ "typos" ]
